//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comet.Game {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comet.Game.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atention! Your account may have been hacked! Someone outside of your network is trying to login..
        /// </summary>
        public static string StrAnotherLoginOtherIp {
            get {
                return ResourceManager.GetString("StrAnotherLoginOtherIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atention! Your account is trying to login from inside of your network!.
        /// </summary>
        public static string StrAnotherLoginSameIp {
            get {
                return ResourceManager.GetString("StrAnotherLoginSameIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot pick up others items..
        /// </summary>
        public static string StrCannotPickupOtherItems {
            get {
                return ResourceManager.GetString("StrCannotPickupOtherItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You are already dead..
        /// </summary>
        public static string StrDead {
            get {
                return ResourceManager.GetString("StrDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has dropped a Dragon Ball in {1}..
        /// </summary>
        public static string StrDragonBallDropped {
            get {
                return ResourceManager.GetString("StrDragonBallDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You`ll pay for what you`ve done!.
        /// </summary>
        public static string StrGuardYouPay {
            get {
                return ResourceManager.GetString("StrGuardYouPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid coordinate..
        /// </summary>
        public static string StrInvalidCoordinate {
            get {
                return ResourceManager.GetString("StrInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid message..
        /// </summary>
        public static string StrInvalidMsg {
            get {
                return ResourceManager.GetString("StrInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} cannot be discarded..
        /// </summary>
        public static string StrItemCannotDiscard {
            get {
                return ResourceManager.GetString("StrItemCannotDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You have been kicked from the game. Reason: {0}..
        /// </summary>
        public static string StrKickout {
            get {
                return ResourceManager.GetString("StrKickout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} extra experience points awarded by killing monsters..
        /// </summary>
        public static string StrKillingExperience {
            get {
                return ResourceManager.GetString("StrKillingExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a None.
        /// </summary>
        public static string StrNone {
            get {
                return ResourceManager.GetString("StrNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You don&apos;t have enough Conquer Points..
        /// </summary>
        public static string StrNotEnoughEmoney {
            get {
                return ResourceManager.GetString("StrNotEnoughEmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You don&apos;t have enough Silvers..
        /// </summary>
        public static string StrNotEnoughMoney {
            get {
                return ResourceManager.GetString("StrNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has become a Baron..
        /// </summary>
        public static string StrPeeragePromptBaron {
            get {
                return ResourceManager.GetString("StrPeeragePromptBaron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has become a Baroness..
        /// </summary>
        public static string StrPeeragePromptBaroness {
            get {
                return ResourceManager.GetString("StrPeeragePromptBaroness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has become a Countess..
        /// </summary>
        public static string StrPeeragePromptCountess {
            get {
                return ResourceManager.GetString("StrPeeragePromptCountess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Congratulations! {0} new Duchess of {1}!.
        /// </summary>
        public static string StrPeeragePromptDuchess {
            get {
                return ResourceManager.GetString("StrPeeragePromptDuchess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Congratulations! {0} new Duke of {1}!.
        /// </summary>
        public static string StrPeeragePromptDuke {
            get {
                return ResourceManager.GetString("StrPeeragePromptDuke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has become an Earl..
        /// </summary>
        public static string StrPeeragePromptEarl {
            get {
                return ResourceManager.GetString("StrPeeragePromptEarl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hear ye, hear ye! All hails to our majesty {0}, new King of {1}!.
        /// </summary>
        public static string StrPeeragePromptKing {
            get {
                return ResourceManager.GetString("StrPeeragePromptKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has become a Knight..
        /// </summary>
        public static string StrPeeragePromptKnight {
            get {
                return ResourceManager.GetString("StrPeeragePromptKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} has become a Lady..
        /// </summary>
        public static string StrPeeragePromptLady {
            get {
                return ResourceManager.GetString("StrPeeragePromptLady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Congratulations! All hails to our highness {0}, Prince of {1}!.
        /// </summary>
        public static string StrPeeragePromptPrince {
            get {
                return ResourceManager.GetString("StrPeeragePromptPrince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Congratulations! All hails to our highness {0}, Princess of {1}!.
        /// </summary>
        public static string StrPeeragePromptPrincess {
            get {
                return ResourceManager.GetString("StrPeeragePromptPrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hear ye, hear ye! All hails to our majesty {0}, new Queen of {1}!.
        /// </summary>
        public static string StrPeeragePromptQueen {
            get {
                return ResourceManager.GetString("StrPeeragePromptQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You picked up {0}..
        /// </summary>
        public static string StrPickupItem {
            get {
                return ResourceManager.GetString("StrPickupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You picked up {0:D0} silvers..
        /// </summary>
        public static string StrPickupSilvers {
            get {
                return ResourceManager.GetString("StrPickupSilvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The target is not in range..
        /// </summary>
        public static string StrTargetNotInRange {
            get {
                return ResourceManager.GetString("StrTargetNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The target is not online..
        /// </summary>
        public static string StrTargetNotOnline {
            get {
                return ResourceManager.GetString("StrTargetNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to use item..
        /// </summary>
        public static string StrUnableToUseItem {
            get {
                return ResourceManager.GetString("StrUnableToUseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your weapon proeficiency level has been improved..
        /// </summary>
        public static string StrWeaponSkillUp {
            get {
                return ResourceManager.GetString("StrWeaponSkillUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your bag is full..
        /// </summary>
        public static string StrYourBagIsFull {
            get {
                return ResourceManager.GetString("StrYourBagIsFull", resourceCulture);
            }
        }
    }
}
