//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comet.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comet.Game.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy for {0} seconds, your hit rate will be increased by {1} percent..
        /// </summary>
        public static string StrAccuracyActiveP {
            get {
                return ResourceManager.GetString("StrAccuracyActiveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy for {0} seconds, your hit rate will be increased by {1} times..
        /// </summary>
        public static string StrAccuracyActiveT {
            get {
                return ResourceManager.GetString("StrAccuracyActiveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atention! Your account may have been hacked! Someone outside of your network is trying to login..
        /// </summary>
        public static string StrAnotherLoginOtherIp {
            get {
                return ResourceManager.GetString("StrAnotherLoginOtherIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atention! Your account is trying to login from inside of your network!.
        /// </summary>
        public static string StrAnotherLoginSameIp {
            get {
                return ResourceManager.GetString("StrAnotherLoginSameIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} has both lost the Qualifier match on a Draw..
        /// </summary>
        public static string StrArenicMatchDraw {
            get {
                return ResourceManager.GetString("StrArenicMatchDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has defeaded {1} in the Qualifier and is currently ranked No. {2}..
        /// </summary>
        public static string StrArenicMatchEnd {
            get {
                return ResourceManager.GetString("StrArenicMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has earned {1} virtue points for helping newbies..
        /// </summary>
        public static string StrAwardVirtue {
            get {
                return ResourceManager.GetString("StrAwardVirtue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have got {0} prizes.  Please find PrizeNPC in the market (185,170) to claim your rewards!.
        /// </summary>
        public static string StrBonus {
            get {
                return ResourceManager.GetString("StrBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a booth set up..
        /// </summary>
        public static string StrBoothAlreadyCreated {
            get {
                return ResourceManager.GetString("StrBoothAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} purchased successfully for {1} {2}..
        /// </summary>
        public static string StrBoothBought {
            get {
                return ResourceManager.GetString("StrBoothBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set up a shop in this map..
        /// </summary>
        public static string StrBoothMapCantSetup {
            get {
                return ResourceManager.GetString("StrBoothMapCantSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than 20 items to your shop..
        /// </summary>
        public static string StrBoothMaxItems {
            get {
                return ResourceManager.GetString("StrBoothMaxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a booth..
        /// </summary>
        public static string StrBoothNoShop {
            get {
                return ResourceManager.GetString("StrBoothNoShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set up a shop in this area..
        /// </summary>
        public static string StrBoothRegionCantSetup {
            get {
                return ResourceManager.GetString("StrBoothRegionCantSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} purchased your {1} for {2} {3}..
        /// </summary>
        public static string StrBoothSold {
            get {
                return ResourceManager.GetString("StrBoothSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t reply to this captcha or give me the wrong answer you&apos;ll be disconnected! Press OK if this equation is correct or Cancel if not. {0} + {1} = {2}?.
        /// </summary>
        public static string StrBotCaptchaMessage {
            get {
                return ResourceManager.GetString("StrBotCaptchaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been sent to the botjail!.
        /// </summary>
        public static string StrBotjail {
            get {
                return ResourceManager.GetString("StrBotjail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} broke up friendship with {1}..
        /// </summary>
        public static string StrBreakFriend {
            get {
                return ResourceManager.GetString("StrBreakFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not blessed and enter the Offline Training Ground..
        /// </summary>
        public static string StrCannotEnterTG {
            get {
                return ResourceManager.GetString("StrCannotEnterTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pick up others items..
        /// </summary>
        public static string StrCannotPickupOtherItems {
            get {
                return ResourceManager.GetString("StrCannotPickupOtherItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is already on it&apos;s maximum composition level..
        /// </summary>
        public static string StrComposeItemMaxComposition {
            get {
                return ResourceManager.GetString("StrComposeItemMaxComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0} has upgraded her {1} to +{2}!.
        /// </summary>
        public static string StrComposeOverpowerFemale {
            get {
                return ResourceManager.GetString("StrComposeOverpowerFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0} has upgraded his {1} to +{2}!.
        /// </summary>
        public static string StrComposeOverpowerMale {
            get {
                return ResourceManager.GetString("StrComposeOverpowerMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPs.
        /// </summary>
        public static string StrConquerPoints {
            get {
                return ResourceManager.GetString("StrConquerPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPs (B).
        /// </summary>
        public static string StrConquerPointsMono {
            get {
                return ResourceManager.GetString("StrConquerPointsMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been severely damaged. Please repair it soon, otherwise it will break..
        /// </summary>
        public static string StrDamagedRepair {
            get {
                return ResourceManager.GetString("StrDamagedRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already dead..
        /// </summary>
        public static string StrDead {
            get {
                return ResourceManager.GetString("StrDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} roared and the teammates XP boosts immediatly..
        /// </summary>
        public static string StrDispatchXp {
            get {
                return ResourceManager.GetString("StrDispatchXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge for {0} seconds, your dodge will be increased by {1} percent..
        /// </summary>
        public static string StrDodgeActiveP {
            get {
                return ResourceManager.GetString("StrDodgeActiveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge for {0} seconds, your dodge will be increased by {1} times..
        /// </summary>
        public static string StrDodgeActiveT {
            get {
                return ResourceManager.GetString("StrDodgeActiveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has dropped a Dragon Ball in {1}..
        /// </summary>
        public static string StrDragonBallDropped {
            get {
                return ResourceManager.GetString("StrDragonBallDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items have been detained by {1}`s help. Please find {2} ({3}, {4}) to redeem within 7 days, or they will be awarded to that player..
        /// </summary>
        public static string StrDropEquip {
            get {
                return ResourceManager.GetString("StrDropEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has dropped part of his equipment for dying as a criminal..
        /// </summary>
        public static string StrDropEquipment {
            get {
                return ResourceManager.GetString("StrDropEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durability of {0} is too low. Please repair it to prevent further damaging..
        /// </summary>
        public static string StrDurabilityRepair {
            get {
                return ResourceManager.GetString("StrDurabilityRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the required item..
        /// </summary>
        public static string StrEmbedNoRequiredItem {
            get {
                return ResourceManager.GetString("StrEmbedNoRequiredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item doesn&apos;t have the second socket open..
        /// </summary>
        public static string StrEmbedNoSecondSocket {
            get {
                return ResourceManager.GetString("StrEmbedNoSecondSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This socket already have a gem in it..
        /// </summary>
        public static string StrEmbedSocketAlreadyFilled {
            get {
                return ResourceManager.GetString("StrEmbedSocketAlreadyFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target item doesn&apos;t have a socket..
        /// </summary>
        public static string StrEmbedTargetNoSocket {
            get {
                return ResourceManager.GetString("StrEmbedTargetNoSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is already locked..
        /// </summary>
        public static string StrEquipLockAlreadyLocked {
            get {
                return ResourceManager.GetString("StrEquipLockAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This equipment is already unlocking..
        /// </summary>
        public static string StrEquipLockAlreadyUnlocking {
            get {
                return ResourceManager.GetString("StrEquipLockAlreadyUnlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This equipment cannot be locked..
        /// </summary>
        public static string StrEquipLockCantLock {
            get {
                return ResourceManager.GetString("StrEquipLockCantLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This equipment is not locked..
        /// </summary>
        public static string StrEquipLockNotLocked {
            get {
                return ResourceManager.GetString("StrEquipLockNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot enter on another event before leave the current one..
        /// </summary>
        public static string StrEventCannotEnterTwoEvents {
            get {
                return ResourceManager.GetString("StrEventCannotEnterTwoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string StrExpired {
            get {
                return ResourceManager.GetString("StrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already using an EXP Potion with better power than this. Wait for the old one to finish..
        /// </summary>
        public static string StrExpPotionInUse {
            get {
                return ResourceManager.GetString("StrExpPotionInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has abdicated the leadership of the family to {1}..
        /// </summary>
        public static string StrFamilyAbdicate {
            get {
                return ResourceManager.GetString("StrFamilyAbdicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has created family {1} successfully..
        /// </summary>
        public static string StrFamilyCreate {
            get {
                return ResourceManager.GetString("StrFamilyCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a new family..
        /// </summary>
        public static string StrFamilyDefaultAnnounce {
            get {
                return ResourceManager.GetString("StrFamilyDefaultAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wife is online..
        /// </summary>
        public static string StrFemaleMateLogin {
            get {
                return ResourceManager.GetString("StrFemaleMateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has claimed the prize for domination of {1} and obtained Level {2} {3:0.00}% EXP..
        /// </summary>
        public static string StrFetchFamilyNpcExpSuccess {
            get {
                return ResourceManager.GetString("StrFetchFamilyNpcExpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clan Leader {0} has claimed the revenue of {1}!.
        /// </summary>
        public static string StrFetchFamilyNpcIncomeSuccess {
            get {
                return ResourceManager.GetString("StrFetchFamilyNpcIncomeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has sent {1} {2} to {3}..
        /// </summary>
        public static string StrFlowerGmPromptAll {
            get {
                return ResourceManager.GetString("StrFlowerGmPromptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already sent flowers today..
        /// </summary>
        public static string StrFlowerHaveSentToday {
            get {
                return ResourceManager.GetString("StrFlowerHaveSentToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t reached level 50!.
        /// </summary>
        public static string StrFlowerLevelTooLow {
            get {
                return ResourceManager.GetString("StrFlowerLevelTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid.
        /// </summary>
        public static string StrFlowerNameLily {
            get {
                return ResourceManager.GetString("StrFlowerNameLily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Rose.
        /// </summary>
        public static string StrFlowerNameRed {
            get {
                return ResourceManager.GetString("StrFlowerNameRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulip.
        /// </summary>
        public static string StrFlowerNameTulip {
            get {
                return ResourceManager.GetString("StrFlowerNameTulip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lily.
        /// </summary>
        public static string StrFlowerNameWhite {
            get {
                return ResourceManager.GetString("StrFlowerNameWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only send flowers to female players..
        /// </summary>
        public static string StrFlowerReceiverNotFemale {
            get {
                return ResourceManager.GetString("StrFlowerReceiverNotFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} send you some flowers..
        /// </summary>
        public static string StrFlowerReceiverPrompt {
            get {
                return ResourceManager.GetString("StrFlowerReceiverPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send flowers when you&apos;re dead..
        /// </summary>
        public static string StrFlowerSenderNotAlive {
            get {
                return ResourceManager.GetString("StrFlowerSenderNotAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only male players can send flowers!.
        /// </summary>
        public static string StrFlowerSenderNotMale {
            get {
                return ResourceManager.GetString("StrFlowerSenderNotMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent flowers..
        /// </summary>
        public static string StrFlowerSendSuccess {
            get {
                return ResourceManager.GetString("StrFlowerSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend list is full..
        /// </summary>
        public static string StrFriendListFull {
            get {
                return ResourceManager.GetString("StrFriendListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has arrested {1}, detained the items and obtained {2} CPs as rewards..
        /// </summary>
        public static string StrGetEmoneyBonus {
            get {
                return ResourceManager.GetString("StrGetEmoneyBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has arrested {1}, and obtained the detained items {2} as rewards after 7 days term..
        /// </summary>
        public static string StrGetEquipBonus {
            get {
                return ResourceManager.GetString("StrGetEquipBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has killed {1} and sent him/her to jail..
        /// </summary>
        public static string StrGoToJail {
            get {
                return ResourceManager.GetString("StrGoToJail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You`ll pay for what you`ve done!.
        /// </summary>
        public static string StrGuardYouPay {
            get {
                return ResourceManager.GetString("StrGuardYouPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target declined your request..
        /// </summary>
        public static string StrGuideDeclined {
            get {
                return ResourceManager.GetString("StrGuideDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent the apprenticeship request..
        /// </summary>
        public static string StrGuideSendStudent {
            get {
                return ResourceManager.GetString("StrGuideSendStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent the apprentice request..
        /// </summary>
        public static string StrGuideSendTutor {
            get {
                return ResourceManager.GetString("StrGuideSendTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target`s level is too high to be your apprentice..
        /// </summary>
        public static string StrGuideStudentHighLevel {
            get {
                return ResourceManager.GetString("StrGuideStudentHighLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target`s level is too low to be your mentor..
        /// </summary>
        public static string StrGuideStudentHighLevel1 {
            get {
                return ResourceManager.GetString("StrGuideStudentHighLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your student, {0}, has logged in..
        /// </summary>
        public static string StrGuideStudentLogin {
            get {
                return ResourceManager.GetString("StrGuideStudentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too many apprentices, and cannot take another..
        /// </summary>
        public static string StrGuideTooManyStudents {
            get {
                return ResourceManager.GetString("StrGuideTooManyStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target has too many apprentices. Please try another..
        /// </summary>
        public static string StrGuideTooManyStudents1 {
            get {
                return ResourceManager.GetString("StrGuideTooManyStudents1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mentor, {0}, has logged in..
        /// </summary>
        public static string StrGuideTutorLogin {
            get {
                return ResourceManager.GetString("StrGuideTutorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t take an apprentice until level 70..
        /// </summary>
        public static string StrGuideTutorLowLevel {
            get {
                return ResourceManager.GetString("StrGuideTutorLowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person under level 70 cannot be your mentor..
        /// </summary>
        public static string StrGuideTutorLowLevel1 {
            get {
                return ResourceManager.GetString("StrGuideTutorLowLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of your items have been detained. Please redeem them within 7 days. Otherwise, you cannot get them back..
        /// </summary>
        public static string StrHasDetainEquip {
            get {
                return ResourceManager.GetString("StrHasDetainEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for arresting {0}. Please find {1} ({2}, {3}) in the market to get rewards..
        /// </summary>
        public static string StrHasEmoneyBonus {
            get {
                return ResourceManager.GetString("StrHasEmoneyBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for arresting {0}, whose items have not been redeemed within 7 days. Find {1} ({2}, {3}) to get these items as rewards..
        /// </summary>
        public static string StrHasEquipBonus {
            get {
                return ResourceManager.GetString("StrHasEquipBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coordinate..
        /// </summary>
        public static string StrInvalidCoordinate {
            get {
                return ResourceManager.GetString("StrInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message..
        /// </summary>
        public static string StrInvalidMsg {
            get {
                return ResourceManager.GetString("StrInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team invitation has been sent..
        /// </summary>
        public static string StrInviteSent {
            get {
                return ResourceManager.GetString("StrInviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item cannot be stored..
        /// </summary>
        public static string StrItemCannotBeStored {
            get {
                return ResourceManager.GetString("StrItemCannotBeStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be discarded..
        /// </summary>
        public static string StrItemCannotDiscard {
            get {
                return ResourceManager.GetString("StrItemCannotDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item cannot be improved..
        /// </summary>
        public static string StrItemCannotImprove {
            get {
                return ResourceManager.GetString("StrItemCannotImprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is already at the maximum level..
        /// </summary>
        public static string StrItemErrMaxLevel {
            get {
                return ResourceManager.GetString("StrItemErrMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is at maximum quality or cannot be upgraded..
        /// </summary>
        public static string StrItemErrMaxQuality {
            get {
                return ResourceManager.GetString("StrItemErrMaxQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a Dragon Ball..
        /// </summary>
        public static string StrItemErrNoDragonBall {
            get {
                return ResourceManager.GetString("StrItemErrNoDragonBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have {0} Dragon Balls..
        /// </summary>
        public static string StrItemErrNotEnoughDragonBalls {
            get {
                return ResourceManager.GetString("StrItemErrNotEnoughDragonBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The equipment level is higher than yours..
        /// </summary>
        public static string StrItemErrNotEnoughLevel {
            get {
                return ResourceManager.GetString("StrItemErrNotEnoughLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have {0} Meteors..
        /// </summary>
        public static string StrItemErrNotEnoughMeteors {
            get {
                return ResourceManager.GetString("StrItemErrNotEnoughMeteors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please repair your item before upgrading..
        /// </summary>
        public static string StrItemErrRepairItem {
            get {
                return ResourceManager.GetString("StrItemErrRepairItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need 5 Meteors to repair your broken equipment..
        /// </summary>
        public static string StrItemErrRepairMeteor {
            get {
                return ResourceManager.GetString("StrItemErrRepairMeteor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed equipment cannot be improved..
        /// </summary>
        public static string StrItemErrUpgradeFixed {
            get {
                return ResourceManager.GetString("StrItemErrUpgradeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target item not found..
        /// </summary>
        public static string StrItemNotFound {
            get {
                return ResourceManager.GetString("StrItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been kicked from the game. Reason: {0}..
        /// </summary>
        public static string StrKickout {
            get {
                return ResourceManager.GetString("StrKickout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You helped detain {0} items. If he/she redeems them within 7 days, you will get what he/she paid as rewards. If not, you will get these items..
        /// </summary>
        public static string StrKillerEquip {
            get {
                return ResourceManager.GetString("StrKillerEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extra experience points awarded by killing monsters..
        /// </summary>
        public static string StrKillingExperience {
            get {
                return ResourceManager.GetString("StrKillingExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are killing too much! You may lose your equipment if killed..
        /// </summary>
        public static string StrKillingTooMuch {
            get {
                return ResourceManager.GetString("StrKillingTooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot lay an NPC there..
        /// </summary>
        public static string StrLayNpcSuperPosition {
            get {
                return ResourceManager.GetString("StrLayNpcSuperPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set a transportation NPC in this map..
        /// </summary>
        public static string StrLayNpcSynTransInvalidMap {
            get {
                return ResourceManager.GetString("StrLayNpcSynTransInvalidMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the Line Skill Tournament..
        /// </summary>
        public static string StrLineSkillPktAnnounce {
            get {
                return ResourceManager.GetString("StrLineSkillPktAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1} has joined the Line Skill Tournament..
        /// </summary>
        public static string StrLineSkillPktAnnounceSyn {
            get {
                return ResourceManager.GetString("StrLineSkillPktAnnounceSyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me: {0:0.00}[{1}/{2}].
        /// </summary>
        public static string StrLineSkillPktOwnRank {
            get {
                return ResourceManager.GetString("StrLineSkillPktOwnRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Skill PK Tournament.
        /// </summary>
        public static string StrLineSkillPktTitleRank {
            get {
                return ResourceManager.GetString("StrLineSkillPktTitleRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº {0} - {1} - {2:0.00}[{3}/{4}].
        /// </summary>
        public static string StrLineSkillPktUsrRank {
            get {
                return ResourceManager.GetString("StrLineSkillPktUsrRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has won {1} from the Lottery..
        /// </summary>
        public static string StrLotteryHigh {
            get {
                return ResourceManager.GetString("StrLotteryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won {0} from the Lottery..
        /// </summary>
        public static string StrLotteryLow {
            get {
                return ResourceManager.GetString("StrLotteryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky! Your equipment durability didn&apos;t decrease after that fail..
        /// </summary>
        public static string StrLuckyGuyNoDuraDown {
            get {
                return ResourceManager.GetString("StrLuckyGuyNoDuraDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky! Your experience has been multiplied by 5 times..
        /// </summary>
        public static string StrLuckyGuyQuintuple {
            get {
                return ResourceManager.GetString("StrLuckyGuyQuintuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky! Your equipment has been upgraded successfully..
        /// </summary>
        public static string StrLuckyGuySuccessUpgrade {
            get {
                return ResourceManager.GetString("StrLuckyGuySuccessUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky! Your equipment has been leveled successfully..
        /// </summary>
        public static string StrLuckyGuySuccessUplevel {
            get {
                return ResourceManager.GetString("StrLuckyGuySuccessUplevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been sent to the macrojail!.
        /// </summary>
        public static string StrMacrojail {
            get {
                return ResourceManager.GetString("StrMacrojail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} are friends from now on..
        /// </summary>
        public static string StrMakeFriend {
            get {
                return ResourceManager.GetString("StrMakeFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to be friends has been sent..
        /// </summary>
        public static string StrMakeFriendSent {
            get {
                return ResourceManager.GetString("StrMakeFriendSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your husband is online..
        /// </summary>
        public static string StrMaleMateLogin {
            get {
                return ResourceManager.GetString("StrMaleMateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot marry a character of the same gender..
        /// </summary>
        public static string StrMarriageErrSameGender {
            get {
                return ResourceManager.GetString("StrMarriageErrSameGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t applied for marriage..
        /// </summary>
        public static string StrMarriageNotApply {
            get {
                return ResourceManager.GetString("StrMarriageNotApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is already married..
        /// </summary>
        public static string StrMarriageTargetNotSingle {
            get {
                return ResourceManager.GetString("StrMarriageTargetNotSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already married..
        /// </summary>
        public static string StrMarriageYouNoSingle {
            get {
                return ResourceManager.GetString("StrMarriageYouNoSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} are pronounced the husband and wife. They promise to love and care for each other for better or worse..
        /// </summary>
        public static string StrMarry {
            get {
                return ResourceManager.GetString("StrMarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target user is pending a captcha reply. Please try again later!.
        /// </summary>
        public static string StrMessageBoxCannotCaptcha {
            get {
                return ResourceManager.GetString("StrMessageBoxCannotCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You found {0}!.
        /// </summary>
        public static string StrMineItemFound {
            get {
                return ResourceManager.GetString("StrMineItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use a pecker to mine..
        /// </summary>
        public static string StrMineWithPecker {
            get {
                return ResourceManager.GetString("StrMineWithPecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have no prize available or it hasn&apos;t been claimed at the event page..
        /// </summary>
        public static string StrNoBonus {
            get {
                return ResourceManager.GetString("StrNoBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not a gem..
        /// </summary>
        public static string StrNoGemEmbed {
            get {
                return ResourceManager.GetString("StrNoGemEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot mine here..
        /// </summary>
        public static string StrNoMine {
            get {
                return ResourceManager.GetString("StrNoMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string StrNone {
            get {
                return ResourceManager.GetString("StrNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inexistent team..
        /// </summary>
        public static string StrNoTeam {
            get {
                return ResourceManager.GetString("StrNoTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in a team..
        /// </summary>
        public static string StrNoTeamToInvite {
            get {
                return ResourceManager.GetString("StrNoTeamToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough Conquer Points..
        /// </summary>
        public static string StrNotEnoughEmoney {
            get {
                return ResourceManager.GetString("StrNotEnoughEmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough in the Clan Fund to apply for the Clan War..
        /// </summary>
        public static string StrNotEnoughFamilyMoneyToChallenge {
            get {
                return ResourceManager.GetString("StrNotEnoughFamilyMoneyToChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t reached the required level..
        /// </summary>
        public static string StrNotEnoughLevel {
            get {
                return ResourceManager.GetString("StrNotEnoughLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough Silvers..
        /// </summary>
        public static string StrNotEnoughMoney {
            get {
                return ResourceManager.GetString("StrNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to leave at least {0} empty spaces in your inventory..
        /// </summary>
        public static string StrNotEnoughSpaceN {
            get {
                return ResourceManager.GetString("StrNotEnoughSpaceN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item cannot be traded..
        /// </summary>
        public static string StrNotToTrade {
            get {
                return ResourceManager.GetString("StrNotToTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is observing your equipments carefully..
        /// </summary>
        public static string StrObservingEquipment {
            get {
                return ResourceManager.GetString("StrObservingEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string StrOpen {
            get {
                return ResourceManager.GetString("StrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This storage is full..
        /// </summary>
        public static string StrPackageFull {
            get {
                return ResourceManager.GetString("StrPackageFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be level 70 or above to donate..
        /// </summary>
        public static string StrPeerageDonateErrBelowLevel {
            get {
                return ResourceManager.GetString("StrPeerageDonateErrBelowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lowest amount you can donate is 3,000,000 silvers..
        /// </summary>
        public static string StrPeerageDonateErrBelowUnderline {
            get {
                return ResourceManager.GetString("StrPeerageDonateErrBelowUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough silvers..
        /// </summary>
        public static string StrPeerageDonateErrNoEnoughMoney {
            get {
                return ResourceManager.GetString("StrPeerageDonateErrNoEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has become a Baron..
        /// </summary>
        public static string StrPeeragePromptBaron {
            get {
                return ResourceManager.GetString("StrPeeragePromptBaron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has become a Baroness..
        /// </summary>
        public static string StrPeeragePromptBaroness {
            get {
                return ResourceManager.GetString("StrPeeragePromptBaroness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has become a Countess..
        /// </summary>
        public static string StrPeeragePromptCountess {
            get {
                return ResourceManager.GetString("StrPeeragePromptCountess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0} new Duchess of {1}!.
        /// </summary>
        public static string StrPeeragePromptDuchess {
            get {
                return ResourceManager.GetString("StrPeeragePromptDuchess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0} new Duke of {1}!.
        /// </summary>
        public static string StrPeeragePromptDuke {
            get {
                return ResourceManager.GetString("StrPeeragePromptDuke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has become an Earl..
        /// </summary>
        public static string StrPeeragePromptEarl {
            get {
                return ResourceManager.GetString("StrPeeragePromptEarl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear ye, hear ye! All hails to our majesty {0}, new King of {1}!.
        /// </summary>
        public static string StrPeeragePromptKing {
            get {
                return ResourceManager.GetString("StrPeeragePromptKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has become a Knight..
        /// </summary>
        public static string StrPeeragePromptKnight {
            get {
                return ResourceManager.GetString("StrPeeragePromptKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has become a Lady..
        /// </summary>
        public static string StrPeeragePromptLady {
            get {
                return ResourceManager.GetString("StrPeeragePromptLady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! All hails to our highness {0}, Prince of {1}!.
        /// </summary>
        public static string StrPeeragePromptPrince {
            get {
                return ResourceManager.GetString("StrPeeragePromptPrince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! All hails to our highness {0}, Princess of {1}!.
        /// </summary>
        public static string StrPeeragePromptPrincess {
            get {
                return ResourceManager.GetString("StrPeeragePromptPrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear ye, hear ye! All hails to our majesty {0}, new Queen of {1}!.
        /// </summary>
        public static string StrPeeragePromptQueen {
            get {
                return ResourceManager.GetString("StrPeeragePromptQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked up {0}..
        /// </summary>
        public static string StrPickupItem {
            get {
                return ResourceManager.GetString("StrPickupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked up {0:D0} silvers..
        /// </summary>
        public static string StrPickupSilvers {
            get {
                return ResourceManager.GetString("StrPickupSilvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has not been found..
        /// </summary>
        public static string StrPigeonAdditionUnexist {
            get {
                return ResourceManager.GetString("StrPigeonAdditionUnexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to submit your message since you have entered nothing..
        /// </summary>
        public static string StrPigeonSendErrEmptyString {
            get {
                return ResourceManager.GetString("StrPigeonSendErrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to broadcast your messages since you do not have enough CPs..
        /// </summary>
        public static string StrPigeonSendErrNoEmoney {
            get {
                return ResourceManager.GetString("StrPigeonSendErrNoEmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to broadcast your message. Please shorten your message..
        /// </summary>
        public static string StrPigeonSendErrStringTooLong {
            get {
                return ResourceManager.GetString("StrPigeonSendErrStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have five messages waiting for broadcast. Please submit again later..
        /// </summary>
        public static string StrPigeonSendOver5Pieces {
            get {
                return ResourceManager.GetString("StrPigeonSendOver5Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations. You have submitted a message for broadcast..
        /// </summary>
        public static string StrPigeonSendProducePrompt {
            get {
                return ResourceManager.GetString("StrPigeonSendProducePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can not mark your message urgent since it has been already broadcast..
        /// </summary>
        public static string StrPigeonUrgentAlreadySent {
            get {
                return ResourceManager.GetString("StrPigeonUrgentAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have enough CPs to submit an urgent message for broadcast..
        /// </summary>
        public static string StrPigeonUrgentErrNoEmoney {
            get {
                return ResourceManager.GetString("StrPigeonUrgentErrNoEmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for helping detain equipment. Please find {0} ({1}, {2}) in the market to get rewards..
        /// </summary>
        public static string StrPkBonus {
            get {
                return ResourceManager.GetString("StrPkBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clan Leader has sent a request to challenge {0}. Prepare yourself!.
        /// </summary>
        public static string StrPrepareToChallengeFamily {
            get {
                return ResourceManager.GetString("StrPrepareToChallengeFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clan Leader has signed up for the Clan War for the domination of {0}. Prepare yourself!.
        /// </summary>
        public static string StrPrepareToChallengeFamilyLogin {
            get {
                return ResourceManager.GetString("StrPrepareToChallengeFamilyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is challenged by other Clan. Prepare yourself!.
        /// </summary>
        public static string StrPrepareToDefendFamily {
            get {
                return ResourceManager.GetString("StrPrepareToDefendFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Clan wants to get the domination of {0} from your clan. Please get ready!.
        /// </summary>
        public static string StrPrepareToDefendFamilyLogin {
            get {
                return ResourceManager.GetString("StrPrepareToDefendFamilyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has redeemed the detained items. {1} CPs has been awarded to {2}..
        /// </summary>
        public static string StrRedeemEquip {
            get {
                return ResourceManager.GetString("StrRedeemEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield for {0} seconds, your defense will be increased by {1} percent..
        /// </summary>
        public static string StrShieldActiveP {
            get {
                return ResourceManager.GetString("StrShieldActiveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield for {0} seconds, your defense will be increased by {1} times..
        /// </summary>
        public static string StrShieldActiveT {
            get {
                return ResourceManager.GetString("StrShieldActiveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silvers.
        /// </summary>
        public static string StrSilvers {
            get {
                return ResourceManager.GetString("StrSilvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll exceed the maximum amount of silvers to store. Can&apos;t exceed {0:N0}..
        /// </summary>
        public static string StrSilversExceedAmount {
            get {
                return ResourceManager.GetString("StrSilversExceedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stigma for {0} seconds, your attack will be increased by {1} percent..
        /// </summary>
        public static string StrStigmaActiveP {
            get {
                return ResourceManager.GetString("StrStigmaActiveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stigma for {0} seconds, your attack will be increased by {1} times..
        /// </summary>
        public static string StrStigmaActiveT {
            get {
                return ResourceManager.GetString("StrStigmaActiveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has killed {1} monsters and is now rank {2} on KO Board..
        /// </summary>
        public static string StrSupermanBroadcast {
            get {
                return ResourceManager.GetString("StrSupermanBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Leader {0} has abdicated the leadership to {1}..
        /// </summary>
        public static string StrSynAbdicate {
            get {
                return ResourceManager.GetString("StrSynAbdicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guild Leader {0} of the Guild {1} has added us to the enemies list..
        /// </summary>
        public static string StrSynAddedEnemy {
            get {
                return ResourceManager.GetString("StrSynAddedEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Leader {0} has added Guild {1} to the enemies list..
        /// </summary>
        public static string StrSynAddEnemy {
            get {
                return ResourceManager.GetString("StrSynAddEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Leader {0} has added Guild {1} to the allies list..
        /// </summary>
        public static string StrSynAllyAdd {
            get {
                return ResourceManager.GetString("StrSynAllyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Leader {0} has removed the Guild {1} from the allies list..
        /// </summary>
        public static string StrSynAllyRemove {
            get {
                return ResourceManager.GetString("StrSynAllyRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guild Leader {0} of {1} has removed our guild from the allies list..
        /// </summary>
        public static string StrSynAllyRemoved {
            get {
                return ResourceManager.GetString("StrSynAllyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in a guild..
        /// </summary>
        public static string StrSynAlreadyJoined {
            get {
                return ResourceManager.GetString("StrSynAlreadyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0} has set up {1} successfully..
        /// </summary>
        public static string StrSynCreate {
            get {
                return ResourceManager.GetString("StrSynCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild {0} has been terminated..
        /// </summary>
        public static string StrSynDestroy {
            get {
                return ResourceManager.GetString("StrSynDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild {0} has accepted your alliance request..
        /// </summary>
        public static string StrSyndicateAllianceAccept {
            get {
                return ResourceManager.GetString("StrSyndicateAllianceAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild {0} has denied your alliance request..
        /// </summary>
        public static string StrSyndicateAllianceDeny {
            get {
                return ResourceManager.GetString("StrSyndicateAllianceDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Guild Leader from {1} is asking to be your ally. Do you accept?.
        /// </summary>
        public static string StrSyndicateAllianceRequest {
            get {
                return ResourceManager.GetString("StrSyndicateAllianceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our {0} {1} has added {2} to the enemies list..
        /// </summary>
        public static string StrSyndicateAntagonize0 {
            get {
                return ResourceManager.GetString("StrSyndicateAntagonize0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} from {2} has added us to the enemies list..
        /// </summary>
        public static string StrSyndicateAntagonize1 {
            get {
                return ResourceManager.GetString("StrSyndicateAntagonize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy {0} {1} from  {2} has killed {3} {4} in {5}!.
        /// </summary>
        public static string StrSyndicateBeKill {
            get {
                return ResourceManager.GetString("StrSyndicateBeKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has killed {3} {4} from {5} in {6}!.
        /// </summary>
        public static string StrSyndicateKill {
            get {
                return ResourceManager.GetString("StrSyndicateKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild {0} has removed us from the allies list..
        /// </summary>
        public static string StrSyndicateNeutral0 {
            get {
                return ResourceManager.GetString("StrSyndicateNeutral0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Guild Leader {0} has removed {1} from the allies list..
        /// </summary>
        public static string StrSyndicateNeutral1 {
            get {
                return ResourceManager.GetString("StrSyndicateNeutral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild {0} has removed us from the enemies list..
        /// </summary>
        public static string StrSyndicatePeace0 {
            get {
                return ResourceManager.GetString("StrSyndicatePeace0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Guild Leader {0} has removed {2} from the enemies list..
        /// </summary>
        public static string StrSyndicatePeace1 {
            get {
                return ResourceManager.GetString("StrSyndicatePeace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has killed {2} {3} in {4}!.
        /// </summary>
        public static string StrSyndicateSameKill {
            get {
                return ResourceManager.GetString("StrSyndicateSameKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has donated {2:N0} Conquer Points to the guild..
        /// </summary>
        public static string StrSynDonateEmoney {
            get {
                return ResourceManager.GetString("StrSynDonateEmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has donated {2:N0} silvers to the guild..
        /// </summary>
        public static string StrSynDonateMoney {
            get {
                return ResourceManager.GetString("StrSynDonateMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to donate {0:N0} to the guild before leaving..
        /// </summary>
        public static string StrSynExitNotEnoughMoney {
            get {
                return ResourceManager.GetString("StrSynExitNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has invited {2} to the guild..
        /// </summary>
        public static string StrSynInviteGuild {
            get {
                return ResourceManager.GetString("StrSynInviteGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has accepted {2} in the guild..
        /// </summary>
        public static string StrSynJoinGuild {
            get {
                return ResourceManager.GetString("StrSynJoinGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left the guild..
        /// </summary>
        public static string StrSynMemberExit {
            get {
                return ResourceManager.GetString("StrSynMemberExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has removed {2} from the guild..
        /// </summary>
        public static string StrSynMemberKickout {
            get {
                return ResourceManager.GetString("StrSynMemberKickout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guild name is already in use..
        /// </summary>
        public static string StrSynNameInUse {
            get {
                return ResourceManager.GetString("StrSynNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot disband this guild..
        /// </summary>
        public static string StrSynNoDisband {
            get {
                return ResourceManager.GetString("StrSynNoDisband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guild needs at least {0:N0} funds to execute actions..
        /// </summary>
        public static string StrSynNoMoney {
            get {
                return ResourceManager.GetString("StrSynNoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the Guild Leader..
        /// </summary>
        public static string StrSynNotLeader {
            get {
                return ResourceManager.GetString("StrSynNotLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0} {1} has promoted {2} to {3}!.
        /// </summary>
        public static string StrSynPromoted {
            get {
                return ResourceManager.GetString("StrSynPromoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guild Leader {0} of {1} has removed our guild from the enemy list..
        /// </summary>
        public static string StrSynRemovedEnemy {
            get {
                return ResourceManager.GetString("StrSynRemovedEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Leader {0} has removed the Guild {1} from the enemy list..
        /// </summary>
        public static string StrSynRemoveEnemy {
            get {
                return ResourceManager.GetString("StrSynRemoveEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP Address has already claimed an reward! You cannot claim it twice..
        /// </summary>
        public static string StrSynWarIpRewarded {
            get {
                return ResourceManager.GetString("StrSynWarIpRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received {0:N0} silvers and {1:N0} CPs for winning the Guild War..
        /// </summary>
        public static string StrSynWarRewardNotify {
            get {
                return ResourceManager.GetString("StrSynWarRewardNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been kicked out of the guild by {0}!.
        /// </summary>
        public static string StrSynYouBeenKicked {
            get {
                return ResourceManager.GetString("StrSynYouBeenKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the Guild Leader..
        /// </summary>
        public static string StrSynYouNoLeader {
            get {
                return ResourceManager.GetString("StrSynYouNoLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your target friend list is full..
        /// </summary>
        public static string StrTargetFriendListFull {
            get {
                return ResourceManager.GetString("StrTargetFriendListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target doen&apos;t have a team..
        /// </summary>
        public static string StrTargetHasNoTeam {
            get {
                return ResourceManager.GetString("StrTargetHasNoTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is not alive..
        /// </summary>
        public static string StrTargetIsNotAlive {
            get {
                return ResourceManager.GetString("StrTargetIsNotAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is not in range..
        /// </summary>
        public static string StrTargetNotInRange {
            get {
                return ResourceManager.GetString("StrTargetNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is not online..
        /// </summary>
        public static string StrTargetNotOnline {
            get {
                return ResourceManager.GetString("StrTargetNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in a team..
        /// </summary>
        public static string StrTeamAlreadyNoJoin {
            get {
                return ResourceManager.GetString("StrTeamAlreadyNoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team application has been sent..
        /// </summary>
        public static string StrTeamApplySent {
            get {
                return ResourceManager.GetString("StrTeamApplySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target team is not accepting new members..
        /// </summary>
        public static string StrTeamClosed {
            get {
                return ResourceManager.GetString("StrTeamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the team leader can dismiss the team..
        /// </summary>
        public static string StrTeamDismissNoLeader {
            get {
                return ResourceManager.GetString("StrTeamDismissNoLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} team experience awarded..
        /// </summary>
        public static string StrTeamExperience {
            get {
                return ResourceManager.GetString("StrTeamExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team is full..
        /// </summary>
        public static string StrTeamFull {
            get {
                return ResourceManager.GetString("StrTeamFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precious: {0}.
        /// </summary>
        public static string StrTeamGems {
            get {
                return ResourceManager.GetString("StrTeamGems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you&apos;re trying to invite does not exist..
        /// </summary>
        public static string StrTeamInvitedNotFound {
            get {
                return ResourceManager.GetString("StrTeamInvitedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        public static string StrTeamItems {
            get {
                return ResourceManager.GetString("StrTeamItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team leader is not alive..
        /// </summary>
        public static string StrTeamLeaderDead {
            get {
                return ResourceManager.GetString("StrTeamLeaderDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The leader is not in range..
        /// </summary>
        public static string StrTeamLeaderNotInRange {
            get {
                return ResourceManager.GetString("StrTeamLeaderNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youa not leader of the team..
        /// </summary>
        public static string StrTeamNoCapitain {
            get {
                return ResourceManager.GetString("StrTeamNoCapitain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target isn&apos;t leader of a team..
        /// </summary>
        public static string StrTeamNoLeader {
            get {
                return ResourceManager.GetString("StrTeamNoLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t been invited to this team..
        /// </summary>
        public static string StrTeamNotInvited {
            get {
                return ResourceManager.GetString("StrTeamNotInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silvers: {0}.
        /// </summary>
        public static string StrTeamSilver {
            get {
                return ResourceManager.GetString("StrTeamSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is already in a team..
        /// </summary>
        public static string StrTeamTargetAlreadyTeam {
            get {
                return ResourceManager.GetString("StrTeamTargetAlreadyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target has not applied for this team..
        /// </summary>
        public static string StrTeamTargetHasNotApplied {
            get {
                return ResourceManager.GetString("StrTeamTargetHasNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is not in range..
        /// </summary>
        public static string StrTeamTargetNotInRange {
            get {
                return ResourceManager.GetString("StrTeamTargetNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has sent you a friend request..
        /// </summary>
        public static string StrToMakeFriend {
            get {
                return ResourceManager.GetString("StrToMakeFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached the limit of {0} items on this arsenal..
        /// </summary>
        public static string StrTotemPoleLimit {
            get {
                return ResourceManager.GetString("StrTotemPoleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already partners..
        /// </summary>
        public static string StrTradeBuddyAlreadyAdded {
            get {
                return ResourceManager.GetString("StrTradeBuddyAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} accepted a trade partnership that will be approved within 3 days..
        /// </summary>
        public static string StrTradeBuddyAnnouncePartnership {
            get {
                return ResourceManager.GetString("StrTradeBuddyAnnouncePartnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} broke the trade partnership with you..
        /// </summary>
        public static string StrTradeBuddyBrokePartnership0 {
            get {
                return ResourceManager.GetString("StrTradeBuddyBrokePartnership0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You broke the trade partnership with {0}..
        /// </summary>
        public static string StrTradeBuddyBrokePartnership1 {
            get {
                return ResourceManager.GetString("StrTradeBuddyBrokePartnership1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner has not been found..
        /// </summary>
        public static string StrTradeBuddyNotFound {
            get {
                return ResourceManager.GetString("StrTradeBuddyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when processing your request..
        /// </summary>
        public static string StrTradeBuddySomethingWrong {
            get {
                return ResourceManager.GetString("StrTradeBuddySomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] You cannot trade more than {0:N0} Conquer Points..
        /// </summary>
        public static string StrTradeMuchEmoney {
            get {
                return ResourceManager.GetString("StrTradeMuchEmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] You cannot trade more than {0:N0} silvers..
        /// </summary>
        public static string StrTradeMuchMoney {
            get {
                return ResourceManager.GetString("StrTradeMuchMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] Your request has been sent..
        /// </summary>
        public static string StrTradeRequestSent {
            get {
                return ResourceManager.GetString("StrTradeRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] You cannot trade more items..
        /// </summary>
        public static string StrTradeSashFull {
            get {
                return ResourceManager.GetString("StrTradeSashFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] Trade success..
        /// </summary>
        public static string StrTradeSuccess {
            get {
                return ResourceManager.GetString("StrTradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] The target is already trading..
        /// </summary>
        public static string StrTradeTargetAlreadyTrade {
            get {
                return ResourceManager.GetString("StrTradeTargetAlreadyTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] The target bag is full..
        /// </summary>
        public static string StrTradeTargetBagIsFull {
            get {
                return ResourceManager.GetString("StrTradeTargetBagIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] You are already trading..
        /// </summary>
        public static string StrTradeYouAlreadyTrade {
            get {
                return ResourceManager.GetString("StrTradeYouAlreadyTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Trade] Your bag is full..
        /// </summary>
        public static string StrTradeYourBagIsFull {
            get {
                return ResourceManager.GetString("StrTradeYourBagIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use item..
        /// </summary>
        public static string StrUnableToUseItem {
            get {
                return ResourceManager.GetString("StrUnableToUseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your equipment received a new socket..
        /// </summary>
        public static string StrUpgradeAwardSocket {
            get {
                return ResourceManager.GetString("StrUpgradeAwardSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have used an item..
        /// </summary>
        public static string StrUseItem {
            get {
                return ResourceManager.GetString("StrUseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You killed a monster and he dropped a {0}..
        /// </summary>
        public static string StrVipDropItem {
            get {
                return ResourceManager.GetString("StrVipDropItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve bound a VIP level {0} which will expire at {1} to your account..
        /// </summary>
        public static string StrVipNotify {
            get {
                return ResourceManager.GetString("StrVipNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War has ended!.
        /// </summary>
        public static string StrWarEnd {
            get {
                return ResourceManager.GetString("StrWarEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. {0}: {1} ({2:N0}).
        /// </summary>
        public static string StrWarRankingNo {
            get {
                return ResourceManager.GetString("StrWarRankingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War Ranking:.
        /// </summary>
        public static string StrWarRankingStart {
            get {
                return ResourceManager.GetString("StrWarRankingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War has begun!.
        /// </summary>
        public static string StrWarStart {
            get {
                return ResourceManager.GetString("StrWarStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dominated the Guild Area!.
        /// </summary>
        public static string StrWarWon {
            get {
                return ResourceManager.GetString("StrWarWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score: {0:N0} Lives: {1}.
        /// </summary>
        public static string StrWarYourScore {
            get {
                return ResourceManager.GetString("StrWarYourScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weapon proficiency couldn&apos;t be upgraded due to your low level..
        /// </summary>
        public static string StrWeaponProfByActionLowLevel {
            get {
                return ResourceManager.GetString("StrWeaponProfByActionLowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weapon proeficiency level has been improved..
        /// </summary>
        public static string StrWeaponSkillUp {
            get {
                return ResourceManager.GetString("StrWeaponSkillUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bag is full..
        /// </summary>
        public static string StrYourBagIsFull {
            get {
                return ResourceManager.GetString("StrYourBagIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target already is your friend..
        /// </summary>
        public static string StrYourFriendAlready {
            get {
                return ResourceManager.GetString("StrYourFriendAlready", resourceCulture);
            }
        }
    }
}
